<LoginScreen>:
  GridLayout: 
  #controls columns
    GridLayout:
      Label:
          text: "User Login"
      TextInput:
        hint_text: "Username"
      TextInput:
        hint_text: "Password"
      Button:
          text: "Login"
    GridLayout:
      cols: 2
      Button:
          text: "Forgot Password?"
      Button:
        text:"Sign Up"


<RootWidget>:
# Logic will be coded in python
  LoginScreen:
    name: "Login_Screen"

# <SignUpScreen>: